services:
  - type: web
    name: tasknest123-api
    env: node
    rootDir: server
    plan: free
    branch: main
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 10000
